version: '3.1'

services:

  db:
    container_name: db
    hostname: db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass